command_dispatch_strategy = "tcp"

[dispatcher.tcp]
max_concurrent_connections = 1
address = "127.0.0.1:4760"
read_buffer_capacity_in_bytes = 1024
frame_prefix_length_in_bytes = 8

[telemetry]
address = "127.0.0.1:9999"
tick_interval_in_seconds = 1 

