name: Cross-compile for Raspberry Pi (2/3/4)

on:
  workflow_call:
    inputs:
      publish-release:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Install cross-compilation dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler && sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Build for Raspberry Pi (2/3/4)
        run: |
          cargo build --release --target=armv7-unknown-linux-gnueabihf --features=pi

      - name: Rename binary
        if: ${{ inputs.publish-release }}
        run: |
          mkdir -p dist
          cp target/armv7-unknown-linux-gnueabihf/release/gpm dist/

      - name: Create GitHub Release
        if: ${{ inputs.publish-release }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
